version: '3.9'

services:

  postgres-postgresql:
    image: postgres:13.4
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job_manager
    ports:
      - "5432:5432"
    restart: always

  web:
    build:
      context: .
      target: development
    container_name: jobs_web_app
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn jobs.main:app --host 0.0.0.0 --port 8123 --reload"
    volumes:
      - .:/opt/jobs/
    ports:
      - "8123:8123"
    depends_on:
      - postgres-postgresql
    restart: on-failure
