apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: convert
  name: convert
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: convert
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: convert
    spec:
      containers:
      - image: {{ .Values.image.registry }}/convert:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: convert
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "2000Mi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: ROOT_PATH
          value: ""
        - name: S3_CREDENTIALS_PROVIDER
          value: "minio"
        - name: MINIO_HOST
          value: "http://minio"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: pipelines
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pipelines
              key: MINIO_SECRET_KEY
        - name: ASSETS_SERVICE_URL
          value: http://{{ .Values.app.hostname }}/api/v1/assets/files/
        - name: CATEGORY_SERVICE_URL
          value: http://{{ .Values.app.hostname }}/api/v1/annotation/categories/
        - name: JOB_SERVICE_URL
          value: http://{{ .Values.app.hostname }}/api/v1/jobs/jobs/
        - name: ANNOTATION_SERVICE_URL
          value: http://{{ .Values.app.hostname }}/api/v1/annotation/
        - name: IMPORT_COCO_URL
          value: http://0.0.0.0:8080/converter/import/
        - name: KEYCLOAK_URL
          value: http://{{ .Values.app.hostname }}
        command: ["/bin/sh"]
        args: ["-c", "uvicorn src.main:app --host 0.0.0.0 --port 8080 --root-path /api/v1/convert"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
