name: models linters and tests

on:
  push:
    paths:
      - models/**
      - .github/worlflows/models.yml
  pull_request:
    paths:
      - models/**
      - .github/worlflows/models.yml
jobs:
   models-linters-and-tests:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: update docker-compose
         run: pip install --upgrade docker-compose
       - name: create base image
         run: cd infra/docker/python_base && make build image_name=818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc/python_base:0.1.7
       - name: run docker-compose up
         run: cd models && docker-compose up -d --build
       - name: run tests
         run: docker exec models_web_app bash -c "pytest"
       - name: check with flake8
         run: docker exec models_web_app bash -c "flake8 --exclude=alembic,tests --extend-ignore=E203"
       - name: check with isort
         run: docker exec models_web_app bash -c "isort --profile=black --line-length=79 --check-only --skip=alembic --skip=tests ."
       - name: check with black
         run: docker exec models_web_app bash -c 'black --check --line-length=79 --exclude="(alembic|tests)" .'
